# Generated by Django 2.0.13 on 2019-07-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingtime',
            name='detail_menu',
            field=models.CharField(choices=[('10', '10분'), ('30', '20분'), ('60', '30분')], default='10', max_length=10),
        ),
    ]
