# Generated by Django 2.2.1 on 2019-07-30 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingtime',
            name='detail_menu',
            field=models.CharField(choices=[('10', '10분'), ('30', '20분'), ('60', '30분')], default='10', max_length=10),
        ),
        migrations.AddField(
            model_name='drivingtime',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
