# Generated by Django 2.0.13 on 2019-07-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_drivingtime_detail_menu'),
        ('main', '0004_auto_20190730_0711'),
    ]

    operations = [
    ]
